"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.injectedDashboardAdminController = exports.injectedFindEventsInAdminSideController = exports.injectedCategoryController = exports.injectedAdminWalletController = exports.injectedVendorStatusController = exports.injectedBlockUnblockController = exports.injectedFindVendorsController = exports.injectedUserManagementController = exports.injectedAdminLoginController = void 0;
const adminRepository_1 = require("../../adapters/repository/admin/adminRepository");
const adminLoginController_1 = require("../../adapters/controllers/admin/authentication/adminLoginController");
const adminLoginUseCase_1 = require("../../useCases/admin/authentication/adminLoginUseCase");
const jwtService_1 = require("../services/jwtService");
const redisService_1 = require("../services/redisService");
const clientBlockUseCase_1 = require("../../useCases/admin/userManagement/clientBlockUseCase");
const clientRespository_1 = require("../../adapters/repository/client/clientRespository");
const clientUnblockUseCase_1 = require("../../useCases/admin/userManagement/clientUnblockUseCase");
const findAllClientUseCase_1 = require("../../useCases/admin/userManagement/findAllClientUseCase");
const vendorDatabase_1 = require("../../adapters/repository/vendor/vendorDatabase");
const findAllVendorUseCase_1 = require("../../useCases/admin/vendorManagement/findAllVendorUseCase");
const findVendorController_1 = require("../../adapters/controllers/admin/vendorManagement/findVendorController");
const vendorBlockUseCase_1 = require("../../useCases/admin/vendorManagement/vendorBlockUseCase");
const vendorBlockUnblockController_1 = require("../../adapters/controllers/admin/vendorManagement/vendorBlockUnblockController");
const vendorUnblockUseCase_1 = require("../../useCases/admin/vendorManagement/vendorUnblockUseCase");
const rejectVendorUseCase_1 = require("../../useCases/admin/vendorManagement/rejectVendorUseCase");
const approveVendorUseCase_1 = require("../../useCases/admin/vendorManagement/approveVendorUseCase");
const vendorStatusController_1 = require("../../adapters/controllers/admin/vendorManagement/vendorStatusController");
const findAllPendingVendorsUseCase_1 = require("../../useCases/admin/vendorManagement/findAllPendingVendorsUseCase");
const userManagementController_1 = require("../../adapters/controllers/admin/userManagement/userManagementController");
const searchClientUseCase_1 = require("../../useCases/admin/userManagement/searchClientUseCase");
const searchVendorUseCase_1 = require("../../useCases/admin/vendorManagement/searchVendorUseCase");
const walletRepository_1 = require("../../adapters/repository/wallet/walletRepository");
const findWalletUseCase_1 = require("../../useCases/wallet/findWalletUseCase");
const walletAdminController_1 = require("../../adapters/controllers/admin/wallet/walletAdminController");
const findTransactionUseCase_1 = require("../../useCases/transaction/findTransactionUseCase");
const transactionRepository_1 = require("../../adapters/repository/transaction/transactionRepository");
const categoryController_1 = require("../../adapters/controllers/admin/categoryManagement/categoryController");
const createCategoryUseCase_1 = require("../../useCases/admin/categoryManagement/createCategoryUseCase");
const updateCategoryUseCase_1 = require("../../useCases/admin/categoryManagement/updateCategoryUseCase");
const findCategoryUseCase_1 = require("../../useCases/admin/categoryManagement/findCategoryUseCase");
const changeCategoryStatusUseCase_1 = require("../../useCases/admin/categoryManagement/changeCategoryStatusUseCase");
const categoryRepository_1 = require("../../adapters/repository/category/categoryRepository");
const findEventsInAdminSide_1 = require("../../useCases/admin/eventManagement/findEventsInAdminSide");
const findEventsInAdminController_1 = require("../../adapters/controllers/admin/eventManagement/findEventsInAdminController");
const eventRepository_1 = require("../../adapters/repository/event/eventRepository");
const findTransactionByPaymentStatusUseCase_1 = require("../../useCases/transaction/findTransactionByPaymentStatusUseCase");
const dashboardDataUseCase_1 = require("../../useCases/admin/dashboard/dashboardDataUseCase");
const eventGraphUseCase_1 = require("../../useCases/admin/dashboard/eventGraphUseCase");
const dashboardController_1 = require("../../adapters/controllers/admin/dahsboard/dashboardController");
const bookingRepository_1 = require("../../adapters/repository/booking/bookingRepository");
const adminRepository = new adminRepository_1.AdminRepository();
const walletRepository = new walletRepository_1.WalletRepository();
const adminLoginUseCase = new adminLoginUseCase_1.AdminLoginUseCase(adminRepository, walletRepository);
const jwtService = new jwtService_1.JwtService();
const redisService = new redisService_1.RedisService();
exports.injectedAdminLoginController = new adminLoginController_1.AdminLoginController(adminLoginUseCase, jwtService, redisService);
const ClientRepository = new clientRespository_1.clientRepository();
//user management
const blockClientUseCase = new clientBlockUseCase_1.BlockClientUseCase(ClientRepository);
const unblockClientUseCase = new clientUnblockUseCase_1.ClientUnblockUseCase(ClientRepository);
const findAllClientUseCase = new findAllClientUseCase_1.FindAllClientUseCase(ClientRepository);
const searchClientUseCase = new searchClientUseCase_1.SearchClientsUseCase(ClientRepository);
exports.injectedUserManagementController = new userManagementController_1.UserManagementController(blockClientUseCase, unblockClientUseCase, findAllClientUseCase, redisService, searchClientUseCase);
//find all vendors , pending vendors
const VendorRepository = new vendorDatabase_1.VendorDatabase();
const findAllVendorUseCase = new findAllVendorUseCase_1.FindAllVendorUseCase(VendorRepository);
const findAllPendingVendorUseCase = new findAllPendingVendorsUseCase_1.FindAllPendingVendorsUseCase(VendorRepository);
exports.injectedFindVendorsController = new findVendorController_1.FindVendorController(findAllVendorUseCase, findAllPendingVendorUseCase);
//block vendor or unblock vendor
const blockVendorUseCase = new vendorBlockUseCase_1.VendorBlockUseCase(VendorRepository);
const unblockVendorUseCase = new vendorUnblockUseCase_1.VendorUnblockUseCase(VendorRepository);
const searchVendorUseCase = new searchVendorUseCase_1.SearchVendorsUseCase(VendorRepository);
exports.injectedBlockUnblockController = new vendorBlockUnblockController_1.VendorBlockUnblockController(unblockVendorUseCase, blockVendorUseCase, searchVendorUseCase, redisService);
//approve vendor or reject vendor
const approveVendorUseCase = new approveVendorUseCase_1.ApproveVendorUseCase(VendorRepository);
const rejectVendorUseCase = new rejectVendorUseCase_1.RejectVendorUseCase(VendorRepository);
exports.injectedVendorStatusController = new vendorStatusController_1.VendorStatusController(approveVendorUseCase, rejectVendorUseCase);
//wallet 
const findWalletAdminUseCase = new findWalletUseCase_1.FindWalletUseCase(walletRepository);
const transactionRepository = new transactionRepository_1.TransactionRepository();
const findTransactionUseCase = new findTransactionUseCase_1.FindTransactionsUseCase(transactionRepository);
const findTransactionByPaymentStatusUseCase = new findTransactionByPaymentStatusUseCase_1.FindTransactionByPaymentUseCase(transactionRepository);
exports.injectedAdminWalletController = new walletAdminController_1.FindAdminWalletDetailsController(findWalletAdminUseCase, findTransactionUseCase, findTransactionByPaymentStatusUseCase);
//category
const categoryRepository = new categoryRepository_1.CategoryDatabaseRepository();
const createCategoryUseCase = new createCategoryUseCase_1.CreateCategoryUseCase(categoryRepository);
const findCategoryUseCase = new findCategoryUseCase_1.FindCategoryUseCase(categoryRepository);
const updateCategoryUseCase = new updateCategoryUseCase_1.UpdateCategoryUseCase(categoryRepository);
const changeCategoryStatusUseCase = new changeCategoryStatusUseCase_1.ChangeCategoryStatusUseCase(categoryRepository);
exports.injectedCategoryController = new categoryController_1.CategoryController(createCategoryUseCase, findCategoryUseCase, updateCategoryUseCase, changeCategoryStatusUseCase);
//events
const eventRepository = new eventRepository_1.EventRepository();
const findEventsInAdminSideUseCase = new findEventsInAdminSide_1.FindEventsInAdminSideUseCase(eventRepository);
exports.injectedFindEventsInAdminSideController = new findEventsInAdminController_1.FindEventsInAdminSideController(findEventsInAdminSideUseCase);
const bookingRepository = new bookingRepository_1.BookingRepository();
const dashboardDataUseCase = new dashboardDataUseCase_1.DashBoardDetailsUseCase(walletRepository, VendorRepository, ClientRepository, bookingRepository, eventRepository);
const eventGraphUseCase = new eventGraphUseCase_1.EventGraphUseCase(eventRepository);
exports.injectedDashboardAdminController = new dashboardController_1.DashboardAdminController(dashboardDataUseCase, eventGraphUseCase);
