"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.injectedVendorStatusCheckingMiddleware = exports.injectedClientStatusCheckingMiddleware = exports.checkAdminMiddleWare = exports.injectedTokenExpiryValidationChecking = exports.injectRefreshTokenAdminController = exports.injectedVendorRefreshTokenController = exports.injectedRefreshTokenController = exports.injectedVerifyTokenAndCheckBlacklistMiddleware = void 0;
const tokenValidationMiddleware_1 = require("../../adapters/middlewares/tokenValidationMiddleware");
const tokenService_1 = require("../services/tokenService");
const redisService_1 = require("../services/redisService");
const jwtService_1 = require("../services/jwtService");
const clientRespository_1 = require("../../adapters/repository/client/clientRespository");
const vendorDatabase_1 = require("../../adapters/repository/vendor/vendorDatabase");
const adminRepository_1 = require("../../adapters/repository/admin/adminRepository");
const tokenTimeExpiryValidation_1 = require("../../adapters/middlewares/tokenTimeExpiryValidation");
const checkAdmin_1 = require("../../adapters/middlewares/admin/checkAdmin");
const ClientStatusChecking_1 = require("../../adapters/middlewares/client/ClientStatusChecking");
const vendorStatusChecking_1 = require("../../adapters/middlewares/vendor/vendorStatusChecking");
const refreshTokenController_1 = require("../../adapters/controllers/auth/refreshTokenController");
const refreshTokenUseCase_1 = require("../../useCases/auth/refreshTokenUseCase");
const refreshTokenVendorController_1 = require("../../adapters/controllers/auth/refreshTokenVendorController");
const refreshTokenAdminController_1 = require("../../adapters/controllers/auth/refreshTokenAdminController");
const redisService = new redisService_1.RedisService();
const jwtService = new jwtService_1.JwtService();
const ACCESSTOKEN_SECRET_KEY = process.env.ACCESSTOKEN_SECRET_KEY;
const tokenService = new tokenService_1.TokenService(redisService, jwtService, ACCESSTOKEN_SECRET_KEY);
exports.injectedVerifyTokenAndCheckBlacklistMiddleware = (0, tokenValidationMiddleware_1.verifyTokenAndCheckBlackList)(tokenService);
//client refresh token
const clientDatabase = new clientRespository_1.clientRepository();
const vendorDatabase = new vendorDatabase_1.VendorDatabase();
const adminRepository = new adminRepository_1.AdminRepository();
const refreshTokenUseCase = new refreshTokenUseCase_1.RefreshTokenUseCase(jwtService, clientDatabase, vendorDatabase, adminRepository);
exports.injectedRefreshTokenController = new refreshTokenController_1.RefreshTokenController(refreshTokenUseCase);
//vendor refresh token
exports.injectedVendorRefreshTokenController = new refreshTokenVendorController_1.RefreshTokenVendorController(refreshTokenUseCase);
exports.injectRefreshTokenAdminController = new refreshTokenAdminController_1.RefreshTokenAdminController(refreshTokenUseCase);
exports.injectedTokenExpiryValidationChecking = (0, tokenTimeExpiryValidation_1.tokenTimeExpiryValidationMiddleware)(jwtService);
exports.checkAdminMiddleWare = (0, checkAdmin_1.checkAdminState)(jwtService, redisService, adminRepository);
const ClientRepository = new clientRespository_1.clientRepository();
exports.injectedClientStatusCheckingMiddleware = (0, ClientStatusChecking_1.clientStatusCheckingMiddleware)(redisService, ClientRepository);
exports.injectedVendorStatusCheckingMiddleware = (0, vendorStatusChecking_1.vendorStatusCheckingMiddleware)(redisService, vendorDatabase);
