"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.injectedBookingVendorController = exports.injectedServiceVendorControllerUseCase = exports.injectedWorkSampleController = exports.injectedTicketVendorController = exports.injectedWalletVendorController = exports.injectedEventController = exports.injectedProfileVendorController = exports.injectedForgotPasswordVendorController = exports.injectedVendorLoginLogoutController = exports.injectedVendorAuthenticationController = void 0;
const emailService_1 = require("../services/emailService");
const otpService_1 = require("../services/otpService");
const vendorDatabase_1 = require("../../adapters/repository/vendor/vendorDatabase");
const clientRespository_1 = require("../../adapters/repository/client/clientRespository");
const userExistenceChecking_1 = require("../services/userExistenceChecking");
const sendOtpVendorUseCase_1 = require("../../useCases/vendor/authentication/sendOtpVendorUseCase");
const registerVendor_1 = require("../../adapters/controllers/vendor/authentication/registerVendor");
const jwtService_1 = require("../services/jwtService");
const redisService_1 = require("../services/redisService");
const vendorRegisterUseCase_1 = require("../../useCases/vendor/authentication/vendorRegisterUseCase");
const loginVendorUseCase_1 = require("../../useCases/vendor/authentication/loginVendorUseCase");
const loginVendor_1 = require("../../adapters/controllers/vendor/authentication/loginVendor");
const sendEmailForgetPasswordVendor_1 = require("../../useCases/vendor/authentication/sendEmailForgetPasswordVendor");
const forgotPasswordVendorController_1 = require("../../adapters/controllers/vendor/authentication/forgotPasswordVendorController");
const forgotPasswordVendorUseCase_1 = require("../../useCases/vendor/authentication/forgotPasswordVendorUseCase");
const resendOtpVendorUseCase_1 = require("../../useCases/vendor/authentication/resendOtpVendorUseCase");
const updateVendorDetailsVendorUseCase_1 = require("../../useCases/vendor/profile/updateVendorDetailsVendorUseCase");
const profileVendorController_1 = require("../../adapters/controllers/vendor/profile/profileVendorController");
const changePasswordVendorUseCase_1 = require("../../useCases/vendor/profile/changePasswordVendorUseCase");
const hashPassword_1 = require("../hashpassword/hashPassword");
const eventRepository_1 = require("../../adapters/repository/event/eventRepository");
const eventCreationUseCase_1 = require("../../useCases/vendor/event/eventCreationUseCase");
const eventController_1 = require("../../adapters/controllers/vendor/event/eventController");
const findAllEventsUseCase_1 = require("../../useCases/vendor/event/findAllEventsUseCase");
const updateEventUseCase_1 = require("../../useCases/vendor/event/updateEventUseCase");
const walletVendorController_1 = require("../../adapters/controllers/vendor/wallet/walletVendorController");
const findWalletUseCase_1 = require("../../useCases/wallet/findWalletUseCase");
const findTransactionUseCase_1 = require("../../useCases/transaction/findTransactionUseCase");
const walletRepository_1 = require("../../adapters/repository/wallet/walletRepository");
const transactionRepository_1 = require("../../adapters/repository/transaction/transactionRepository");
const ticketVendorController_1 = require("../../adapters/controllers/vendor/ticket/ticketVendorController");
const ticketAndUserDetailsofEventUseCase_1 = require("../../useCases/vendor/ticket/ticketAndUserDetailsofEventUseCase");
const ticketRepository_1 = require("../../adapters/repository/ticket/ticketRepository");
const vendorLogoutUseCase_1 = require("../../useCases/vendor/authentication/vendorLogoutUseCase");
const workSampleRepository_1 = require("../../adapters/repository/workSamples/workSampleRepository");
const workSampleCreationUseCase_1 = require("../../useCases/vendor/workSample/workSampleCreationUseCase");
const findWorkSampleofVendor_1 = require("../../useCases/vendor/workSample/findWorkSampleofVendor");
const workSampleController_1 = require("../../adapters/controllers/vendor/workSample/workSampleController");
const createServiceUseCase_1 = require("../../useCases/vendor/service/createServiceUseCase");
const editServiceUseCase_1 = require("../../useCases/vendor/service/editServiceUseCase");
const changeStatusServiceUseCase_1 = require("../../useCases/vendor/service/changeStatusServiceUseCase");
const findServiceUseCase_1 = require("../../useCases/vendor/service/findServiceUseCase");
const serviceRepository_1 = require("../../adapters/repository/service/serviceRepository");
const serviceVendorController_1 = require("../../adapters/controllers/vendor/services/serviceVendorController");
const categoryRepository_1 = require("../../adapters/repository/category/categoryRepository");
const findCategoryUseCase_1 = require("../../useCases/vendor/service/findCategoryUseCase");
const bookingRepository_1 = require("../../adapters/repository/booking/bookingRepository");
const showBookingsInVendor_1 = require("../../useCases/vendor/booking/showBookingsInVendor");
const approveBookingsInVendor_1 = require("../../useCases/vendor/booking/approveBookingsInVendor");
const rejectBookingVendorUseCase_1 = require("../../useCases/vendor/booking/rejectBookingVendorUseCase");
const updateBookingAsCompletedUseCase_1 = require("../../useCases/vendor/booking/updateBookingAsCompletedUseCase");
const bookingVendorController_1 = require("../../adapters/controllers/vendor/booking/bookingVendorController");
const ticketVerificationUseCase_1 = require("../../useCases/vendor/ticket/ticketVerificationUseCase");
const findTransactionByPaymentStatusUseCase_1 = require("../../useCases/transaction/findTransactionByPaymentStatusUseCase");
const EmailService = new emailService_1.emailService();
const otpService = new otpService_1.OtpService();
const vendorRepository = new vendorDatabase_1.VendorDatabase();
const clientDatabase = new clientRespository_1.clientRepository();
const UserExistence = new userExistenceChecking_1.userExistence(clientDatabase, vendorRepository);
const injectedVendorRegisterUsecase = new vendorRegisterUseCase_1.VendorRegisterUseCase(vendorRepository);
const sendOtpVendorUseCase = new sendOtpVendorUseCase_1.SendOtpVendorUseCase(EmailService, otpService, UserExistence);
const resendOtpVendorUseCase = new resendOtpVendorUseCase_1.ResendOtpVendorUseCase(EmailService, otpService);
exports.injectedVendorAuthenticationController = new registerVendor_1.VendorAuthenticationController(injectedVendorRegisterUsecase, sendOtpVendorUseCase, resendOtpVendorUseCase);
//login vendor
const vendorLoginUseCase = new loginVendorUseCase_1.LoginVendorUseCase(vendorRepository);
const jwtService = new jwtService_1.JwtService();
const redisService = new redisService_1.RedisService();
const vendorLogoutUseCase = new vendorLogoutUseCase_1.VendorLogoutUseCase(redisService, jwtService);
exports.injectedVendorLoginLogoutController = new loginVendor_1.LoginLogoutVendorController(vendorLoginUseCase, jwtService, redisService, vendorLogoutUseCase);
// forgot password
const SendEmailForgetPasswordVendor = new sendEmailForgetPasswordVendor_1.sendEmailForgetPasswordVendor(EmailService, jwtService, vendorRepository);
const resetPasswordVendorUseCase = new forgotPasswordVendorUseCase_1.ResetPasswordVendorUseCase(jwtService, vendorRepository);
exports.injectedForgotPasswordVendorController = new forgotPasswordVendorController_1.ForgotPasswordVendorController(SendEmailForgetPasswordVendor, resetPasswordVendorUseCase);
//Vendor profile 
const Hashpassword = new hashPassword_1.hashPassword();
const changePasswordVendorUseCase = new changePasswordVendorUseCase_1.ChangePasswordVendorUseCase(vendorRepository, Hashpassword);
const UpdateDetailsVendorUseCase = new updateVendorDetailsVendorUseCase_1.updateDetailsVendorUseCase(vendorRepository);
exports.injectedProfileVendorController = new profileVendorController_1.ProfileVendorController(changePasswordVendorUseCase, UpdateDetailsVendorUseCase);
//event creation
const eventRepository = new eventRepository_1.EventRepository();
const eventCreationUseCase = new eventCreationUseCase_1.EventCreationUseCase(eventRepository);
const findAllEventsUseCase = new findAllEventsUseCase_1.FindAllEventsVendorUseCase(eventRepository);
const updateEventUseCase = new updateEventUseCase_1.UpdateEventUseCase(eventRepository);
exports.injectedEventController = new eventController_1.EventController(eventCreationUseCase, findAllEventsUseCase, updateEventUseCase);
//wallet
const walletRepository = new walletRepository_1.WalletRepository();
const transactionRepository = new transactionRepository_1.TransactionRepository();
const findWalletUseCase = new findWalletUseCase_1.FindWalletUseCase(walletRepository);
const findTransactionUseCase = new findTransactionUseCase_1.FindTransactionsUseCase(transactionRepository);
const findTransactionByPaymentStatusUseCase = new findTransactionByPaymentStatusUseCase_1.FindTransactionByPaymentUseCase(transactionRepository);
exports.injectedWalletVendorController = new walletVendorController_1.WalletVendorController(findWalletUseCase, findTransactionUseCase, findTransactionByPaymentStatusUseCase);
//ticket
const ticketRepository = new ticketRepository_1.TicketRepository();
const ticketAndUserDetailsOfEventUseCase = new ticketAndUserDetailsofEventUseCase_1.TicketAndUserDetailsOfEventUseCase(ticketRepository);
const ticketVerificationUseCase = new ticketVerificationUseCase_1.TicketVerificationUseCase(ticketRepository, eventRepository);
exports.injectedTicketVendorController = new ticketVendorController_1.TicketVendorController(ticketAndUserDetailsOfEventUseCase, ticketVerificationUseCase);
//workSample
const workSampleRepository = new workSampleRepository_1.WorkSampleRepository();
const workSampleCreationUseCase = new workSampleCreationUseCase_1.WorkSampleCreationUseCase(workSampleRepository);
const findWorkSampleofVendorUseCase = new findWorkSampleofVendor_1.FindWorkSamplesOfAVendorUseCase(workSampleRepository);
exports.injectedWorkSampleController = new workSampleController_1.WorkSampleController(workSampleCreationUseCase, findWorkSampleofVendorUseCase);
//service
const categoryRepository = new categoryRepository_1.CategoryDatabaseRepository();
const serviceRepository = new serviceRepository_1.ServiceRepository();
const findCategoryForCreatingService = new findCategoryUseCase_1.FindCategoryForServiceUseCase(categoryRepository);
const createServiceUseCase = new createServiceUseCase_1.CreateServiceUseCase(serviceRepository);
const editServiceUseCase = new editServiceUseCase_1.EditServiceUseCase(serviceRepository);
const changeStatusServiceUseCase = new changeStatusServiceUseCase_1.ChangeStatusServiceUseCase(serviceRepository);
const findServiceUseCase = new findServiceUseCase_1.FindServiceUseCase(serviceRepository);
exports.injectedServiceVendorControllerUseCase = new serviceVendorController_1.ServiceVendorController(findCategoryForCreatingService, createServiceUseCase, editServiceUseCase, changeStatusServiceUseCase, findServiceUseCase);
//bookings
const bookingRepository = new bookingRepository_1.BookingRepository();
const showBookingsInVendorUseCase = new showBookingsInVendor_1.ShowBookingsInVendorUseCase(bookingRepository);
const approveBookingVendorUseCase = new approveBookingsInVendor_1.ApproveBookingUseCase(bookingRepository);
const rejectBookingVendorUseCase = new rejectBookingVendorUseCase_1.RejectBookingInVendorUseCase(bookingRepository);
const updateBookingAsCompleteUseCase = new updateBookingAsCompletedUseCase_1.UpdateBookingAsCompleteUseCase(bookingRepository);
exports.injectedBookingVendorController = new bookingVendorController_1.BookingsVendorController(showBookingsInVendorUseCase, approveBookingVendorUseCase, rejectBookingVendorUseCase, updateBookingAsCompleteUseCase);
